config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :kiosk_layouts
  resources :date_ranges
  resources :directories
  # Api namespaced routes and modules
  # ie: /api/v1/hours => Api::V1::HoursController#show
  namespace :api, defaults: { format: :json } do
    namespace :v1, constraints: Api::V1::Constraints.new(version: 1,
                                                         default: true) do
      post    'hours' => 'hours#show'
      get     'rooms/available/:start_time' => 'rooms#available'
    end
  end

  resources :collections
  resources :slides
  resources :slide_types
  resources :kiosks do
    collection do
      get :edit_multiple
      put :update_multiple
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/kiosk', :to => 'kiosk#index', :as => 'kiosk_index'
  get '/kiosk/:id', :to => 'kiosk#show', :as => 'kiosk_show'

  # Directory Paths
  get '/directory/iframe_page', :to => 'directories#iframe_page', :as => 'iframe_page'

  post '/uploads/:collection_id', to: 'slides#create'
  # This is a hack that is required because the rails form the uploader is on
  # sets the _method parameter to patch when the work already exists.
  # Eventually it would be good to update the javascript so that it doesn't
  # submit the form, just the file and always uses POST.
  patch '/uploads/:collection_id', to: 'slides#create'

  root to: 'kiosk#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
# frozen_string_literal: true

# Collection is a grouping of related slides
class Collection < ApplicationRecord
  # attr_accessor :slides_attributes
  has_many :slides, inverse_of: :collection, dependent: :destroy
  belongs_to :primary_slide, class_name: 'Slide', optional: true, touch: true
  validates :name, presence: true
  accepts_nested_attributes_for :slides, reject_if: proc { |attributes| attributes[:title].blank? }, allow_destroy: true
end

app/models/slide.rb
# frozen_string_literal: true

# Slides are the primary representation of the media on display at the various kiosks
class Slide < ApplicationRecord
  after_save :touch_kiosks
  include Rails.application.routes.url_helpers
  attr_accessor :image, :video, :subtitles
  belongs_to :slide_type

  has_many :kiosk_slides, dependent: :destroy
  has_many :kiosks, through: :kiosk_slides

  belongs_to :collection, inverse_of: :slides

  has_many :date_ranges, inverse_of: :slide, dependent: :destroy
  accepts_nested_attributes_for :date_ranges, allow_destroy: true

  validates :title, :caption, presence: true

  mount_uploader :video, VideoUploader
  mount_uploaders :subtitles, SubtitleUploader
  serialize :subtitles, JSON
  mount_uploader :image, ImageUploader

  def to_jq_upload
    {
      'name' => read_attribute(:image),
      'size' => image.size,
      'url' => image.url,
      'thumbnailUrl' => image.thumb.url,
      'deleteUrl' => slide_path(id: id),
      'deleteType' => 'DELETE',
      'title' => read_attribute(:title),
      'caption' => read_attribute(:caption),
      'id' => id
    }
  end

  def subtitle_filename(index)
    File.basename subtitles[index].url if subtitles[index].present?
  end

  def touch_kiosks
    kiosks.each(&:touch)
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

# Controller for collections of slides
class CollectionsController < ApplicationController
  before_action :find_collection, only: %i[show edit update destroy]
  before_action :related_models, only: %i[new show edit update destroy]
  before_action :authenticate_user!
  before_action :authorize

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show; end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit; end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    build_kiosks(params)
    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    upload_slides(params)
    build_kiosks(params)
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def find_collection
    @collection = Collection.find(params[:id])
  end

  def upload_slides(params)
    return unless params['commit'] == 'Upload Slides'

    params['uploaded_files'].each do |fid|
      s = Slide.find(fid)
      s.collection_id = params['id']
      s.save!
    end
  end

  def build_kiosks(params)
    return unless params[:collection] && params[:collection][:slides_attributes]

    slides = {}
    params[:collection][:slides_attributes].each do |k, v|
      slide_id = v ? v['id'] : k['id']
      slide_kiosks = v ? v['kiosk_ids'] : k['kiosk_ids']
      slides[slide_id] = slide_kiosks if slide_id
    end

    @collection.slides.each do |slide|
      slide_id = slide.id.to_s
      kiosks = []
      if slides.key? slide_id
        slides[slide_id].each do |k|
          kiosks << Kiosk.find(k)
        end
      end

      if params['commit'] == 'Upload Slides'
        slide.kiosks = kiosks if slides.key? slide_id
      else
        slide.kiosks = kiosks
      end
    end
  end

  def related_models
    @kiosks = Kiosk.all
    @slide_types = SlideType.all
    @default_kiosk = Kiosk.find_or_create_by(name: 'touch')
    @default_slide_type = SlideType.find_or_create_by(name: 'Basic')
    @kiosk_options = Kiosk.all.collect { |obj| { obj.name => obj.id } }.inject(:merge)
    @slide_type_options = SlideType.all.collect { |obj| { obj.name => obj.id } }.inject(:merge)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collection_params
    params.require(:collection).permit(
      :detail,
      :name,
      :primary_slide_id,
      slides_attributes: [
        :id,
        :caption,
        :expires_at,
        :title,
        :collection_id,
        :slide_type_id,
        :image,
        :_destroy,
        { date_ranges_attributes: %i[id start_date end_date slide_id _destroy] }
      ]
    )
  end

  def authorize
    unless current_user&.admin?
      flash[:alert] = 'You do not have sufficient permissions to view this page'
      redirect_to root_path
    end
  end
end

app/views/collections/_collection_add_slide_form.html.erb
<%= form_for collection, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
  <!-- <div id="fileupload"> -->

  <!-- Redirect browsers with JavaScript disabled to the origin page -->
  <noscript><input type="hidden" name="redirect" value="<%= main_app.root_path %>"></noscript>
  <!-- The table listing the files available for upload/download -->
  <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>

  <h2>Upload Local Slides</h2>
  <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->

    <!-- The collection ID to pass to the upload controller -->
    <input id="collection_id" type="hidden" value="<%= collection.id %>">
    <div class="row fileupload-buttonbar">
      <div class="col-xs-7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <span class="glyphicon glyphicon-plus"></span>
          <span>Add files...</span>
          <input type="file" name="files[]" multiple>
        </span>
         <button type="reset" class="btn btn-warning cancel hidden">
          <span class="glyphicon glyphicon-ban-circle"></span>
          <span>Cancel upload</span>
        </button>

        <div class="actions">
          <input type="submit" name="commit" value="Upload Slides" class="btn btn-primary upload-slides hidden" data-disable-with="Update Collection">
        </div>

        <!-- The global file processing state -->
        <span class="fileupload-process"></span>
      </div>
      <!-- The global progress state -->
      <div class="col-xs-5 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
          <div class="progress-bar progress-bar-success" style="width:0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div class="progress-extended">&nbsp;</div>
      </div>
    </div>

  <div class="dropzone">

  </div>
<!-- </div> -->

<% end %>

app/views/collections/_collection_slide.html.erb
<td><%= image_tag(slide.image_url(:thumb)) if slide.image_url(:thumb) %> <%= "Primary Slide" if primary_slide %></td>
<td><%= link_to slide.title, slide %></td>
<td>
  <ul>
    <% for date_range in slide.date_ranges %>
      <li><%= date_range.start_date.strftime("%m/%d/%y") %> - <%= date_range.end_date.strftime("%m/%d/%y") %></li>
    <% end %>
  </ul>
</td>
<td>
  <ul>
    <% for kiosk in slide.kiosks %>
      <li>
        <%= link_to kiosk.name, kiosk_show_path(id: kiosk.name) %>
      </li>
    <% end %>
  </ul>
</td>
<td><%= link_to 'View', slide %></td>
<td><%= link_to 'Edit', edit_slide_path(slide) %></td>
<td><%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/collections/_edit_slides_in_collection.html.erb
<h2>Edit slides in collection</h1>
  <hr style="border: 1px solid darkgrey;">
  <div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Field Name</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :slides do |builder, index| %>
          <tr>
            <th scope="row">
              <strong>Slide:</strong><br>
              <%= image_tag(builder.object.image_url(:thumb)) if builder.object.image_url(:thumb) %>
            </th>
            <td>
              <fieldset>
                <div class="field">
                  <%= builder.label :image %>
                  <%= builder.file_field :image, required: false, class: "form-control" %>
                </div>

                <div class="field">
                  <%= builder.label :caption %>
                  <%= builder.text_area :caption, required: true,class: "form-control" %>
                </div>

                <div class="field">
                  <%= builder.label :date_ranges, 'Display Dates' %>
                  <ul class="list-group" id="list-group-date-ranges">
                    <%= builder.fields_for :date_ranges do |g| %>
                      <%= render partial: 'slides/date_range_fields', :locals => { f: g } %>
                    <% end %>
                    <%= link_to_add_date_ranges "Add Date Range", builder, :date_ranges %>
                  </ul>
                </div>

                <div class="field">
                  <%= builder.label :title %>
                  <%= builder.text_field :title, required: true, class: "form-control" %>
                </div>

                <div class="field">
                  <%= builder.label :slide_type_id %>
                  <%= builder.select('slide_type_id', options_from_collection_for_select(slide_types, :id, :name, builder.object.slide_type_id), { :include_blank => '-- Select One --' }, :required => true, class: "form-control") %>
                </div>

                <%= builder.label :kiosks %>
                <div class="field">
                  <ul class="list-group">
                    <span class="ul">
                      <% kiosks.each do |kiosk| %>
                        <label class="li"><%= check_box_tag :kiosks, kiosk.id, builder.object.kiosks.include?(kiosk), :name => 'collection[slides_attributes]['+builder.index.to_s+'][kiosk_ids][]' %> <u><%= kiosk.name %></u></label><br />
                      <% end %>
                    </span>
                  </ul>
                </div>

              </fieldset>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="actions">
      <%= f.submit "Update Slides", class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/collections/_form.html.erb
<%= form_for collection, :html => {:multipart => true} do |f| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Edit collection</h2>
  <%= link_to 'View Collection', @collection, class: "btn btn-default pull-right collection-show-buttons collection-button-move-left" %>
  <%= link_to 'All Collections', collections_path, class: "btn btn-default pull-right collection-show-buttons" %>

  <hr style="border: 1px solid darkgrey;">
  <div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :detail %>
      <%= f.text_area :detail, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :primary_slide %>
      <%= f.select('primary_slide_id', options_from_collection_for_select(collection.slides, :id, :title, f.object.primary_slide_id), { :include_blank => '-- Select One --' }, :required => false, class: "form-control") %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

  &nbsp;
  &nbsp;

  <% if !collection.slides.blank? %>
    <%= render :partial => "edit_slides_in_collection", :locals => {f:f, slide_types:@slide_types, kiosks:@kiosks } %>
  <% end %>

   
<% end %>

app/views/collections/_js_templates.html.erb
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>

<!-- function used by the following template -->
<script type="text/javascript">
  function setAllDefaultOptions(fileId,fieldName) {
    var firstFile = $("#collection_slides_attributes_" + fileId.toString() + "_" + fieldName)[0];
    var selected_options = [];
    for (var i = 0; i < firstFile.length; i++) {
      if (firstFile.options[i].selected) {
        selected_options.push(firstFile.options[i].value);
      }
    }
    $("." + fieldName + "_dropdown").each(function(index, element) {
      for(var i=0; i< this.length; i++) {
        this.options[i].selected =
          $.inArray(this.options[i].value, selected_options) > -1 ? true : false;
      }
    });
  }
</script>

<!-- The template to display files available for download -->
<script id="batch-template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
          <div class="row">
            <div class="col-sm-2">
                <span class="preview">
                    {% if (file.thumbnailUrl) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                    {% } %}
                </span>
            </div>
            <div class="col-sm-4 name">
                <span>{%=file.name%}</span>
                <input type="hidden" name="uploaded_files[]" value="{%=file.id%}">
            </div>
            <div class="col-sm-6">
              {% if (file.error) { %}
                  <div><span class="label label-danger">Error</span> {%=file.error%}</div>
              {% } %}
              <span class="size">{%=o.formatFileSize(file.size)%}</span>
              <button class="btn btn-danger delete pull-right" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                  <i class="glyphicon glyphicon-trash"></i>
                  <span>Delete</span>
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12 form-horizontal">
              <div class="form-group">
                <label for="collection_slides_attributes_{%=file.id%}_title" class="col-sm-5 control-label">Slide Title</label>
                <div class="col-sm-7">
                  <input type="text" class="form-control" name="collection[slides_attributes][{%=file.id%}][title]" id="collection_slides_attributes_{%=file.id%}_title" value="{%=file.title%}">
                </div>

                <label for="collection_slides_attributes_{%=file.id%}_caption" class="col-sm-5 control-label">Slide Caption</label>
                <div class="col-sm-7">
                  <input type="text" class="form-control" name="collection[slides_attributes][{%=file.id%}][caption]" id="collection_slides_attributes_{%=file.id%}_caption" value="{%=file.caption%}">
                </div>

                <label for="collection_slides_attributes_{%=file.id%}_date_ranges" class="col-sm-5 control-label">Display Dates and Times</label>
                <div class="col-sm-7">
                  <div class="slides-to-be-uploaded" id="uploaded-slide-{%=file.id%}" data-id="{%=file.id%}">
                    <%= fields_for Slide.new do |f| %>
                      <%= link_to_add_date_ranges_new_collection "Add Date Range", f, :date_ranges, "{%=file.id%}" %>
                    <% end %>
                  </div>
                </div>

                <label for="collection_slides_attributes_{%=file.id%}_slide_type_id" class="col-sm-5 control-label">Slide Type</label>
                <div class="col-sm-7">
                  <select class="form-control slide_type_id_dropdown" multiple="multiple" size="" name="collection[slides_attributes][{%=file.id%}][slide_type_id]" id="collection_slides_attributes_{%=file.id%}_slide_type_id" value="{%=file.slide_type%}">
                    <%= options_for_select(slide_type_options, default_slide_type_id)  %>
                  </select>
                  <button class="btn pull-right slide_type_button" onClick="setAllDefaultOptions({%= file.id %}, 'slide_type_id'); return false;">Set all to this Slide Type</button>
                </div>

                <label for="collection_slides_attributes_kiosks" class="col-sm-5 control-label">Kiosks</label>
                <div class="col-sm-7">
                  <ul class="list-group">
                    <span class="ul">
                      <% kiosks.each do |kiosk| %>
<label class="li"><%= check_box_tag :kiosks, kiosk.id, false, :name => 'collection[slides_attributes][{%=file.id%}][kiosk_ids][]' %> <u><%= kiosk.name %></u></label><br />
                      <% end %>
                    </span>
                  </ul>
                </div>

                <input type="hidden" value="{%= file.id %}" name="collection[slides_attributes][{%= file.id %}][id]" id="collection_slides_attributes_{%= file.id %}_id">
                <input type="hidden" <%= "value=#{collection_id}" %> name="collection[slides_attributes][{%= file.id %}][collection_id]" id="collection_slides_attributes_{%= file.id %}_collection_id">
              </div>
            </div>
          </div>
        </td>
    </tr>
{% } %}
</script>

<!-- Simpler display of files available for download. Originally from hyrax/base/_form_files -->
<!-- TODO: further consolidate with template-download above -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
                <input type="hidden" name="uploaded_files[]" value="{%=file.id%}">
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
        </td>
    </tr>
{% } %}
</script>

app/views/collections/edit.html.erb
<%= render 'form', collection: @collection %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Collections</h1>
<%= link_to 'New Collection', new_collection_path, class: "btn btn-primary pull-right collection-show-buttons" %>
<hr style="border: 1px solid darkgrey;">

<h2>All collections</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Slides</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @collections.each do |collection| %>
        <% if collection.name != "generic" %>
          <tr>
            <td><%= link_to collection.name, collection %></td>
            <td>
              <%= collection.slides.count.to_s %>
            </td>
            <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
            <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<br>

app/views/collections/new.html.erb
<h1>New Collection</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @collection, :html => {:multipart => true} do |f| %>
      <% if @collection.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>
          <ul>
            <% @collection.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <h2>Create new collection</h2>
      <div>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to 'All Collections', collections_path, class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/collections/show.html.erb
<h1><%= @collection.name %></h1>
<label>Detail</label>
<%= @collection.detail %>
<%= link_to 'Edit Collection', edit_collection_path(@collection), class: "btn btn-primary pull-right collection-show-buttons" %>
<%= link_to 'All Collections', collections_path, class: "btn btn-default pull-right collection-show-buttons" %>

<hr style="border: 1px solid darkgrey;">

<h2>Slides in collection</h2>
  <!-- Table -->
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Slide</th>
        <th>Title</th>
        <th>Caption</th>
        <th>Display Dates</th>
        <th>Kiosk</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% unless @collection.primary_slide.nil? %>
        <tr>
          <%= render 'collection_slide', slide: @collection.primary_slide, primary_slide: true %>
        </tr>
      <% end %>
      <% @collection.slides.each do |slide| %>
        <% next if slide.title == @collection.primary_slide&.title %>
        <tr>
          <%= render 'collection_slide', slide: slide, primary_slide: false %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= render 'collection_add_slide_form', collection: @collection %>
</div>

<%= render partial: 'collections/js_templates', :locals => {
  :collection_id => @collection.id,
  :collection => @collection,
  :default_kiosk_id => @default_kiosk.id,
  :default_slide_type_id => @default_slide_type.id,
  :kiosk_options => @kiosk_options,
  :slide_type_options => @slide_type_options,
  :kiosks => @kiosks
} %>