config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :kiosk_layouts
  resources :date_ranges
  resources :directories
  # Api namespaced routes and modules
  # ie: /api/v1/hours => Api::V1::HoursController#show
  namespace :api, defaults: { format: :json } do
    namespace :v1, constraints: Api::V1::Constraints.new(version: 1,
                                                         default: true) do
      post    'hours' => 'hours#show'
      get     'rooms/available/:start_time' => 'rooms#available'
    end
  end

  resources :collections
  resources :slides
  resources :slide_types
  resources :kiosks do
    collection do
      get :edit_multiple
      put :update_multiple
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/kiosk', :to => 'kiosk#index', :as => 'kiosk_index'
  get '/kiosk/:id', :to => 'kiosk#show', :as => 'kiosk_show'

  # Directory Paths
  get '/directory/iframe_page', :to => 'directories#iframe_page', :as => 'iframe_page'

  post '/uploads/:collection_id', to: 'slides#create'
  # This is a hack that is required because the rails form the uploader is on
  # sets the _method parameter to patch when the work already exists.
  # Eventually it would be good to update the javascript so that it doesn't
  # submit the form, just the file and always uses POST.
  patch '/uploads/:collection_id', to: 'slides#create'

  root to: 'kiosk#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slide.rb
# frozen_string_literal: true

# Slides are the primary representation of the media on display at the various kiosks
class Slide < ApplicationRecord
  after_save :touch_kiosks
  include Rails.application.routes.url_helpers
  attr_accessor :image, :video, :subtitles
  belongs_to :slide_type

  has_many :kiosk_slides, dependent: :destroy
  has_many :kiosks, through: :kiosk_slides

  belongs_to :collection, inverse_of: :slides

  has_many :date_ranges, inverse_of: :slide, dependent: :destroy
  accepts_nested_attributes_for :date_ranges, allow_destroy: true

  validates :title, :caption, presence: true

  mount_uploader :video, VideoUploader
  mount_uploaders :subtitles, SubtitleUploader
  serialize :subtitles, JSON
  mount_uploader :image, ImageUploader

  def to_jq_upload
    {
      'name' => read_attribute(:image),
      'size' => image.size,
      'url' => image.url,
      'thumbnailUrl' => image.thumb.url,
      'deleteUrl' => slide_path(id: id),
      'deleteType' => 'DELETE',
      'title' => read_attribute(:title),
      'caption' => read_attribute(:caption),
      'id' => id
    }
  end

  def subtitle_filename(index)
    File.basename subtitles[index].url if subtitles[index].present?
  end

  def touch_kiosks
    kiosks.each(&:touch)
  end
end

app/models/slide_type.rb
# frozen_string_literal: true

# Slide types were used to drive the original donor kiosk
class SlideType < ApplicationRecord
  has_many :slides
  validates :name, presence: true
end

app/controllers/slides_controller.rb
# frozen_string_literal: true

# Controller to manage slides related to kiosks
class SlidesController < ApplicationController
  before_action :find_slide, only: %i[show edit update destroy]
  before_action :related_models, only: %i[create new show edit update destroy]
  before_action :default_kiosk, only: %i[create new edit update destroy]
  before_action :default_slide_type, only: %i[create new edit update destroy]
  before_action :default_collection, only: %i[create new edit update destroy]
  before_action :authenticate_user!
  before_action :authorize

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show; end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit; end

  # POST /slides
  # POST /slides.json
  def create
    if params[:files]
      default_title = params[:files].first.original_filename.to_s
      default_params = { image: params[:files].first, caption: 'Enter Caption', title: default_title, expires_at: Date.today, slide_type_id: @default_slide_type.id, collection_id: @default_collection.id }
      @slide = Slide.new(default_params)
    else
      @slide = Slide.new(slide_params)
    end

    build_kiosks(params)
    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json do
          render json: { files: [@slide.to_jq_upload] }
        end.to_json
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }.to_json
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    build_kiosks(params)
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def find_slide
    @slide = Slide.find(params[:id])
  end

  def build_kiosks(params)
    kiosk_ids = params.dig('slide', 'kiosk_ids').try(:reject, &:empty?)
    @slide.kiosks = kiosk_ids ? Kiosk.find(kiosk_ids) : []
  end

  def related_models
    @kiosks = Kiosk.all
    @slide_types = SlideType.all
    @collections = Collection.all
  end

  def default_kiosk
    @default_kiosk = Kiosk.find_by_name('touch')
  end

  def default_slide_type
    @default_slide_type = SlideType.find_by_name('Basic')
  end

  def default_collection
    @default_collection = Collection.find_by_name('generic') unless params[:collection_id].present?
    @default_collection = Collection.find(params[:collection_id]) if params[:collection_id].present?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def slide_params
    params.require(:slide).permit(:caption, :expires_at, :title, :description, :collection_id, :slide_type_id, :image, :video, :kiosk_ids, { subtitles: [] }, date_ranges_attributes: %i[id start_date end_date _destroy])
  end

  def authorize
    unless current_user&.admin?
      flash[:alert] = 'You do not have sufficient permissions to view this page'
      redirect_to root_path
    end
  end
end

app/views/slides/_active_slides_form.html.erb
<%# NEW FORM: Create a form displaying all the active slides %>
<h2>Active Slides</h2>

<br/>

<table id="active_slides" class="table table-striped">
  <thead>
    <tr>
      <th>Slide</th>
      <th>Title</th>
      <th>Caption</th>
      <th>Collection</th>
      <th>Start Display Date</th>
      <th>End Display Date</th>
      <th>Kiosks</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @slides.each do |slide| %>
    <% if (!slide.date_ranges.empty?) && (Time.now.to_i <= slide.date_ranges.last.end_date.to_i) && (Time.now.to_i >= slide.date_ranges.last.start_date.to_i) %>
      <tr>
        <td><%= image_tag(slide.image_url(:thumb)) if slide.image_url(:thumb) %></td>
        <td><%= link_to slide.title, slide %></td>
        <td><%= slide.caption %></td>
        <td><%= link_to(slide.collection.name, collection_path(slide.collection.id)) if slide && slide.collection %></td>
        <td><%= slide.date_ranges.last.start_date.strftime("%m/%d/%y") unless slide.date_ranges.empty? %></td>
        <td><%= slide.date_ranges.last.end_date.strftime("%m/%d/%y") unless slide.date_ranges.empty? %></td>
        <td>
          <ul>
            <% for kiosk in slide.kiosks %>
              <li>
                <%= link_to kiosk.name, kiosk_show_path(id: kiosk.name) %>
              </li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <li><%= link_to 'View', slide %></li>
            <li><%= link_to 'Edit', edit_slide_path(slide) %></li>
            <li><%= link_to 'Delete', slide, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/slides/_all_slides_form.html.erb
<%# NEW FORM: Create a form displaying all the slides %>
<h2>All Slides</h2>

<br/>

<table id="slides" class="table table-striped">
  <thead>
    <tr>
      <th>Slide</th>
      <th>Title</th>
      <th>Caption</th>
      <th>Collection</th>
      <th>Start Display Date</th>
      <th>End Display Date</th>
      <th>Kiosks</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @slides.each do |slide| %>
    <tr>
      <td><%= image_tag(slide.image_url(:thumb)) if slide.image_url(:thumb) %></td>
      <td><%= link_to slide.title, slide %></td>
      <td><%= slide.caption %></td>
      <td><%= link_to(slide.collection.name, collection_path(slide.collection.id)) if slide && slide.collection %></td>
      <td><%= slide.date_ranges.last.start_date.strftime("%m/%d/%y") unless slide.date_ranges.empty? %></td>
      <td><%= slide.date_ranges.last.end_date.strftime("%m/%d/%y") unless slide.date_ranges.empty? %></td>
      <td>
        <ul>
          <% for kiosk in slide.kiosks %>
            <li>
              <%= link_to kiosk.name, kiosk_show_path(id: kiosk.name) %>
            </li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <li><%= link_to 'View', slide %></li>
          <li><%= link_to 'Edit', edit_slide_path(slide) %></li>
          <li><%= link_to 'Delete', slide, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/slides/_date_range_fields.html.erb
<fieldset>
  <li class="list-group-item">
    <div class="row">
      <div class="col-xs-5">
        <%= f.label :start_date, "Start Date" %><br>
        <%= f.datetime_select :start_date, {}, {class: 'datetime-form-control'} %><br>
      </div>
      <div class="col-xs-5">
        <%= f.label :end_date, "End Date" %><br>
        <%= f.datetime_select :end_date, {}, {class: 'datetime-form-control'} %>
      </div>
      <div class="col-xs-2">
        <%= f.hidden_field :_destroy %>
        <%= link_to "remove", '#', class: "remove_fields btn btn-danger" %>
      </div>
    </div>
  </li>
</fieldset>

app/views/slides/_form.html.erb
<%= simple_form_for slide , html: { multipart: true } do |f| %>
  <% if slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide.errors.count, "error") %> prohibited this slide from being saved:</h2>
      <ul>
        <% slide.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <hr style="border: 1px solid darkgrey">

  <div class="row">
    <div class="col-xs-12 col-md-12">
      <h2>Enter Slide Values</h2>
      <%= f.input :title, required: true %>
      <%= f.input :caption, required: true %>
      <%= f.input :image, as: :file %>
      <%= f.input :collection_id, collection: @collections, as: :select, selected: slide.collection_id ? slide.collection_id : @default_collection.id %>
      <%= f.input :slide_type_id, collection: @slide_types, as: :select, selected: slide.slide_type_id ? slide.slide_type_id : @default_slide_type.id %>
      <%= f.association :kiosks, as: :check_boxes, collection: @kiosks, selected: slide.kiosks %>
    </div>
  </div>

  <hr style="border: 1px solid darkgrey">

  <div class="row">
    <div class="col-xs-12 col-md-12">
      <h2>Audio/Video Values</h2>
      <%= f.input :description %>
      <%= f.input :video, as: :file %>
      <%= f.input :subtitles, as: :file, label: 'English Subtitles (vtt)', input_html: { name: 'slide[subtitles][]'} %>
      <%= f.input :subtitles, as: :file, label: 'Spanish Subtitles (vtt)', input_html: { name: 'slide[subtitles][]'} %>
    </div>
  </div>

  <hr style="border: 1px solid darkgrey">

  <div class="row">
    <div class="col-xs-12 col-md-12">
      <div class="panel-display-dates">
        <h2><%= f.label :date_ranges, "Display dates and times" %></h2>
        <div class="field">
          <ul class="list-group" id="list-group-date-ranges">
            <%= f.fields_for :date_ranges do |builder| %>
              <%= render 'date_range_fields', f: builder %>
            <% end %>
            <%= link_to_add_date_ranges "Add Date Range", f, :date_ranges %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/slides/edit.html.erb
<h1>Editing Slide</h1>

<%= render 'form', slide: @slide, slide_types: @slide_types, kiosks: @kiosks, collections: @collections %>

app/views/slides/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Slide', new_slide_path, class: "btn btn-primary pull-right" %>
<h1>Slides</h1>
<hr style="border: 1px solid darkgrey;">

<%# TAB: Setup the tab layout to have filter content for slides %>
<div class="tabs" role="main">
  <%# UL: Create an unordered list to setup the filter %>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="nav-item">
      <a class="nav-link" href="#active_slides" aria-controls="active_slides" role="tab" data-toggle="tab">
        <%= 'Active Slides' %>
      </a>
    </li>

    <li role="presentation" class="nav-item">
      <a class="nav-link" href="#all_slides" aria-controls="all_slides" role="tab" data-toggle="tab">
        <%= 'All Slides' %>
      </a>
    </li>
  </ul>

  <%# SUB-CONTENT: Create the tab content card to display and render the form %>
  <div class="tab-content card">
    <div role="tabpanel" class="tab-pane" id="active_slides">
      <div class="form-tab-content">
        <%= render "active_slides_form" %>
      </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="all_slides">
      <div class="form-tab-content">
        <%= render "all_slides_form" %>
      </div>
    </div>
  </div>
</div>

app/views/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form', slide: @slide %>
<%= link_to 'Back', slides_path, class: "btn btn-default" %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_slide_path(@slide), class: "btn btn-primary pull-right" %>
<h2>Slide Info</h2>
<hr style="border: 1px solid darkgrey">
<h3><%= @slide.title%></h3>
<table class="table table-striped">
  <thead>
  </thead>
  <tbody>
    <tr>
      <th>Caption:</th>
      <td><%= @slide.caption %></td>
    </tr>
    <tr>
      <th>Description:</th>
      <td><%= @slide.description %></td>
    </tr>
    <tr>
      <th>English Subtitles:</th>
      <td>
        <ul>
          <% @slide.subtitles.each_with_index do |subtitle, index| %>
            <li><%= link_to(@slide.subtitle_filename(index), subtitle.url) %></li>
          <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <th>Display dates:</th>
      <td>
        <ul>
          <% for date_range in @slide.date_ranges %>
            <li><%= date_range.start_date.strftime("%m/%d/%Y %I:%M:%S %p") %> - <%= date_range.end_date.strftime("%m/%d/%Y %I:%M:%S %p") %></li>
          <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <th>Slide type:</th>
      <td><%= @slide.slide_type.name %></td>
    </tr>
    <tr>
      <th>Slide Collection:</th>
      <td><%= link_to(@slide.collection.name, collection_path(@slide.collection.id)) if @slide && @slide.collection %></td>
    </tr>
    <tr>
      <th>Kiosks:</th>
      <td>
        <ul>
          <% for kiosk in @slide.kiosks %>
            <li><%= link_to kiosk.name, kiosk_show_path(id: kiosk.name) %></li>
          <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <th>Image:</th>
      <td><%= image_tag @slide.image_url(:large).to_s %></td>
    </tr>
    <tr>
      <th><strong>Image Sizes</strong><br></th>
      <td>
        <%= link_to "x-large", @slide.image_url(:xlarge).to_s %> | 
        <%= link_to "large", @slide.image_url(:large).to_s %> | 
        <%= link_to "medium", @slide.image_url(:medium).to_s %> | 
        <%= link_to "original", @slide.image_url.to_s %>
      </td>
    </tr>
  </tbody>
</table>