config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :kiosk_layouts
  resources :date_ranges
  resources :directories
  # Api namespaced routes and modules
  # ie: /api/v1/hours => Api::V1::HoursController#show
  namespace :api, defaults: { format: :json } do
    namespace :v1, constraints: Api::V1::Constraints.new(version: 1,
                                                         default: true) do
      post    'hours' => 'hours#show'
      get     'rooms/available/:start_time' => 'rooms#available'
    end
  end

  resources :collections
  resources :slides
  resources :slide_types
  resources :kiosks do
    collection do
      get :edit_multiple
      put :update_multiple
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/kiosk', :to => 'kiosk#index', :as => 'kiosk_index'
  get '/kiosk/:id', :to => 'kiosk#show', :as => 'kiosk_show'

  # Directory Paths
  get '/directory/iframe_page', :to => 'directories#iframe_page', :as => 'iframe_page'

  post '/uploads/:collection_id', to: 'slides#create'
  # This is a hack that is required because the rails form the uploader is on
  # sets the _method parameter to patch when the work already exists.
  # Eventually it would be good to update the javascript so that it doesn't
  # submit the form, just the file and always uses POST.
  patch '/uploads/:collection_id', to: 'slides#create'

  root to: 'kiosk#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/slide_types_controller.rb
# frozen_string_literal: true

# Controller for managing slide types
class SlideTypesController < ApplicationController
  before_action :set_slide_type, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authorize

  # GET /slide_types
  # GET /slide_types.json
  def index
    @slide_types = SlideType.all
  end

  # GET /slide_types/1
  # GET /slide_types/1.json
  def show; end

  # GET /slide_types/new
  def new
    @slide_type = SlideType.new
  end

  # GET /slide_types/1/edit
  def edit; end

  # POST /slide_types
  # POST /slide_types.json
  def create
    @slide_type = SlideType.new(slide_type_params)

    respond_to do |format|
      if @slide_type.save
        format.html { redirect_to @slide_type, notice: 'Slide type was successfully created.' }
        format.json { render :show, status: :created, location: @slide_type }
      else
        format.html { render :new }
        format.json { render json: @slide_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slide_types/1
  # PATCH/PUT /slide_types/1.json
  def update
    respond_to do |format|
      if @slide_type.update(slide_type_params)
        format.html { redirect_to @slide_type, notice: 'Slide type was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide_type }
      else
        format.html { render :edit }
        format.json { render json: @slide_type.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_slide_type
    @slide_type = SlideType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def slide_type_params
    params.require(:slide_type).permit(:name)
  end

  def authorize
    unless current_user&.admin?
      flash[:alert] = 'You do not have sufficient permissions to view this page'
      redirect_to root_path
    end
  end
end

app/views/slide_types/_form.html.erb
<%= form_for(slide_type) do |f| %>
  <% if slide_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide_type.errors.count, "error") %> prohibited this slide_type from being saved:</h2>

      <ul>
      <% slide_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/slide_types/edit.html.erb
<h1>Editing Slide Type</h1>

<%= render 'form', slide_type: @slide_type %>

<%= link_to 'Show', @slide_type, class: "btn btn-primary" %>
<%= link_to 'Back', slide_types_path, class: "btn btn-default" %>

app/views/slide_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slide Types</h1>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h2 class="panel-title">All Slide Types</h2>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @slide_types.each do |slide_type| %>
        <tr>
          <td><%= slide_type.name %></td>
          <td><%= link_to 'Show', slide_type %></td>
          <td><%= link_to 'Edit', edit_slide_type_path(slide_type) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div> 

<br>

<%= link_to 'New Slide Type', new_slide_type_path, class: "btn btn-primary" %>
<%= link_to 'Admin Panel', rails_admin_path, class: "btn btn-default" %>

app/views/slide_types/new.html.erb
<h1>New Slide Type</h1>

<%= render 'form', slide_type: @slide_type %>

<%= link_to 'Back', slide_types_path, class: "btn btn-default" %>

app/views/slide_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide_type.name %>
</p>

<%= link_to 'Edit', edit_slide_type_path(@slide_type) %> |
<%= link_to 'Back', slide_types_path %>