config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :kiosk_layouts
  resources :date_ranges
  resources :directories
  # Api namespaced routes and modules
  # ie: /api/v1/hours => Api::V1::HoursController#show
  namespace :api, defaults: { format: :json } do
    namespace :v1, constraints: Api::V1::Constraints.new(version: 1,
                                                         default: true) do
      post    'hours' => 'hours#show'
      get     'rooms/available/:start_time' => 'rooms#available'
    end
  end

  resources :collections
  resources :slides
  resources :slide_types
  resources :kiosks do
    collection do
      get :edit_multiple
      put :update_multiple
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/kiosk', :to => 'kiosk#index', :as => 'kiosk_index'
  get '/kiosk/:id', :to => 'kiosk#show', :as => 'kiosk_show'

  # Directory Paths
  get '/directory/iframe_page', :to => 'directories#iframe_page', :as => 'iframe_page'

  post '/uploads/:collection_id', to: 'slides#create'
  # This is a hack that is required because the rails form the uploader is on
  # sets the _method parameter to patch when the work already exists.
  # Eventually it would be good to update the javascript so that it doesn't
  # submit the form, just the file and always uses POST.
  patch '/uploads/:collection_id', to: 'slides#create'

  root to: 'kiosk#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kiosk.rb
# frozen_string_literal: true

# Kiosk records relate to individual screens
class Kiosk < ApplicationRecord
  belongs_to :kiosk_layout, touch: true
  has_many :kiosk_slides, dependent: :destroy
  has_many :slides, through: :kiosk_slides
  validates :name, presence: true
  validate :restart_at_cannot_be_in_the_past

  def restart_at_cannot_be_in_the_past
    errors.add(:restart_at, "(#{restart_at}) can't be in the past, please select a date in the future, or click 'Clear' to remove the date.") if restart_at.present? && restart_at < Time.now
  end

  def should_restart?
    restart_at_active && restart_at < Time.now && restart_at > 1.minutes.ago
  end

  def restart_pending?
    restart_at_active && (restart_at > Time.now || restart_at > 1.minutes.ago)
  end

  def slide_length_ms
    (slide_length || 5) * 1000
  end
end

app/controllers/kiosk_controller.rb
# frozen_string_literal: true

# Controller for managing kiosks
class KioskController < ApplicationController
  layout 'react_application', except: [:index]
  before_action :set_kiosk_params, only: [:index]
  before_action :set_maps_params, only: [:show]

  def index; end

  def show
    @kiosk = Kiosk.find_by(name: params[:id])
    @restart_kiosk = false.to_s
    @directory_ecampus = Directory.where(content: 'Ecampus Leadership').to_json
    @directory_osulp = Directory.where(content: 'OSULP Leadership').to_json
    if reload_kiosk?(@kiosk)
      @restart_kiosk = true.to_s
      Rails.logger.info "restarting #{@kiosk.name} kiosk"
    end

    # get only slides that have current date ranges, given a time (i.e now, Time.zone.parse("20160503050000"), etc)
    @slides = @kiosk.slides.joins(:date_ranges).where('date_ranges.start_date <= ? AND date_ranges.end_date >= ?', Time.zone.now, Time.zone.now)
    @api_uri = ENV['PRIMO_API_URI'] || ''
  end

  private

  def reload_kiosk?(kiosk)
    return false if kiosk.restart_at.nil? || kiosk.restart_at_active.nil?

    kiosk.should_restart?
  end

  def set_kiosk_params
    @kiosks = Kiosk.all
  end

  def set_maps_params
    @maps = APPLICATION_CONFIG['maps'].map { |m| { title: m['title'], image_url: m['image_url'] } }
    @maps_base_url = ENV['MAPS_BASE_URL']
  end
end

app/controllers/kiosks_controller.rb
# frozen_string_literal: true

# Controller for rendering the kiosk UIs
class KiosksController < ApplicationController
  before_action :set_kiosk, only: %i[show edit update destroy]
  before_action :set_options, only: %i[create new show edit update destroy]
  before_action :authenticate_user!
  before_action :authorize
  before_action :set_params

  # GET /kiosks
  # GET /kiosks.json
  def index
    @kiosks = Kiosk.all
  end

  # GET /kiosks/1
  # GET /kiosks/1.json
  def show; end

  # GET /kiosks/new
  def new
    @kiosk = Kiosk.new
  end

  # GET /kiosks/1/edit
  def edit; end

  # POST /kiosks
  # POST /kiosks.json
  def create
    @kiosk = Kiosk.new(kiosk_params)

    respond_to do |format|
      if @kiosk.save
        format.html { redirect_to @kiosk, notice: 'Kiosk was successfully created.' }
        format.json { render :show, status: :created, location: @kiosk }
      else
        format.html { render :new }
        format.json { render json: @kiosk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kiosks/1
  # PATCH/PUT /kiosks/1.json
  def update
    respond_to do |format|
      if @kiosk.update(kiosk_params)
        format.html { redirect_to @kiosk, notice: 'Kiosk was successfully updated.' }
        format.json { render :show, status: :ok, location: @kiosk }
      else
        format.html { render :edit }
        format.json { render json: @kiosk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @kiosk.destroy
    respond_to do |format|
      format.html { redirect_to kiosks_url, notice: 'Kiosk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /kiosks/1/edit_multiple
  def edit_multiple
    @kiosks = Kiosk.find(params[:kiosk_ids])
  end

  # PATCH/PUT /kiosks/1/update_multiple
  def update_multiple
    @kiosks = Kiosk.find(params[:kiosk_ids])
    @kiosks.reject! do |kiosk|
      kiosk.update_attributes(kiosk_params_multiple)
    end

    if @kiosks.empty?
      redirect_to kiosks_url
    else
      @kiosk = Kiosk.new(kiosk_params_multiple)
      render 'edit_multiple'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_kiosk
    @kiosk = Kiosk.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kiosk_params
    params.require(:kiosk).permit(:name, :map_default_floor_number, :slide_length, :kiosk_layout_id, :restart_at, :restart_at_active)
  end

  # Only allow restart_at and restart_at_active (restart status) for mass update
  def kiosk_params_multiple
    params.require(:kiosk).permit(:restart_at, :restart_at_active)
  end

  def set_options
    @kiosk_layouts = KioskLayout.all
  end

  def set_params
    @kiosk_type ||= params[:id]
    # TODO: replace this with current slides for a specific kiosk type
    @slides = [{
      id: 1,
      image_url: '/uploads/default_slide_1.png',
      expires_at: '2020-12-31T23:59:59Z',
      created_at: '2000-12-31T11:59:59Z',
      updated_at: '2000-12-31T23:59:59Z',
      title: 'Slide.title',
      caption: 'Slide.caption',
      slide_type: 'SlideType.name',
      kiosk: 'Kiosk.name'
    }, {
      id: 2,
      image_url: '/uploads/default_slide_2.png',
      expires_at: '2010-11-11T13:00:00Z',
      created_at: '2000-11-11T11:00:00Z',
      updated_at: '2000-11-11T13:00:00Z',
      title: 'Slide.title:2',
      caption: 'Slide.caption:2',
      slide_type: 'SlideType.name:2',
      kiosk: 'Kiosk.name:2'
    }]
  end

  def authorize
    unless current_user&.admin?
      flash[:alert] = 'You do not have sufficient permissions to view this page'
      redirect_to root_path
    end
  end
end

app/views/kiosks/_form.html.erb
<%= form_for(kiosk) do |f| %>
  <% if kiosk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kiosk.errors.count, "error") %> prohibited this kiosk from being saved:</h2>

      <ul>
        <% kiosk.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :kiosk_layout_id %>
        <%= f.select('kiosk_layout_id', options_from_collection_for_select(@kiosk_layouts, :id, :name, kiosk.kiosk_layout_id), { :include_blank => '-- Select One --' }, :required => true, class: "form-control") %>
      </div>
      <div class="field">
        <%= f.label :map_default_floor_number %>
        <%= f.text_field :map_default_floor_number, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label "Slide Length (in seconds)" %>
        <%= f.number_field :slide_length, class: "form-control", min: 5 %>
      </div>
      <div class="field">
        <%= f.label :restart_at_active, "Enable restarting kiosk" %>
        <%= f.check_box :restart_at_active, {:class => "enable_restart_at"} %>
      </div>

      <div class="field restart_at">
        <%= f.label :restart_at, "Restart kiosk at" %><br>
        <%= f.datetime_select :restart_at, {:include_blank => true, :select => DateTime.now}, {class: 'datetime-form-control form-inline'} %>
        <button type="button" id="set_today_btn" class="btn btn-default" autocomplete="off">
          Set to Today
        </button>
        <button type="button" id="clear_restart_at_btn" class="btn btn-default" autocomplete="off">
          Clear
        </button>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/kiosks/edit.html.erb
<h1>Editing Kiosk</h1>
<%= render 'form', kiosk: @kiosk %>

app/views/kiosks/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Kiosk', new_kiosk_path, class: "btn btn-primary pull-right" %>
<h1>Kiosks</h1>
<hr style="border: 1px solid darkgrey;">

<%= form_tag edit_multiple_kiosks_path, method: :get do %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Map Default Floor Number (if applicable)</th>
        <th>Slide Length (in seconds)</th>
        <th>Restart Status</th>
        <th>Restart Date/time</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @kiosks.each do |kiosk| %>
        <tr>
          <td><%= link_to kiosk.name, kiosk %></td>
          <td><%= kiosk.map_default_floor_number %></td>
          <td><%= kiosk.slide_length %></td>
          <td>
            <% if kiosk.restart_at_active == true %>
              <% if kiosk.restart_pending? %>
                <span class="label label-danger">Pending</span>
              <% else %>
                <span class="label label-default">Restarted</span>
              <% end %>
            <% else %>
              <span class="label label-default">Restarted</span>
            <% end %>
          </td>
          <td><%= kiosk.restart_at %></td>
          <td><%= link_to 'Show', kiosk_show_path(id: kiosk.name) %></td>
          <td><%= link_to 'Edit', edit_kiosk_path(kiosk) %></td>
          <td><%= link_to 'Destroy', kiosk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/kiosks/new.html.erb
<h1>New Kiosk</h1>
<%= render 'form', kiosk: @kiosk %>

app/views/kiosks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Kiosk Info</h2>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Field Name</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">
          <strong>Name:</strong>
        </th>
        <td>
          <p>
          <%= @kiosk.name %>
          </p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <strong>Maps Default Floor Number:</strong>
        </th>
        <td>
          <p>
          <%= @kiosk.map_default_floor_number %>
          </p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <strong>Restart status</strong>
        </th>
        <td>
          <p>
            <% if @kiosk.restart_at_active == true %>
              <span class="label label-danger">Pending</span>
            <% else %>
              <span class="label label-default">Restarted</span>
            <% end %>
          </p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <strong>Restart at:</strong>
        </th>
        <td>
          <p>
          <%= @kiosk.restart_at %>
          </p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <strong>Slide Length (in seconds):</strong>
        </th>
        <td>
          <p>
          <%= @kiosk.slide_length %>
          </p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <strong>Layout Name:</strong>
        </th>
        <td>
          <p>
            <%= @kiosk.kiosk_layout.name %>
          </p>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_kiosk_path(@kiosk), class: "btn btn-primary" %>
<%= link_to 'All Kiosks', kiosks_path, class: "btn btn-default" %>